[versions]
android-plugin = "7.3.1"
androidx-activity = "1.3.1"
androidx-compose = "1.2.0"
androidx-compose-compiler = "1.2.0"

[libraries]
android-tools-desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.2.0" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.7.0" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha11" }

[bundles]
androidx-compose = [
    "androidx-activity-compose",
    "androidx-compose-runtime",
    "androidx-compose-foundation",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
]
androidx-compose-debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.7.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.13.1" }
