[versions]
android-plugin = "7.3.1"
compose = "1.2.0"
compose-compiler = "1.2.0"

[libraries]
android-tools-desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.2.0" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.7.0" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.3.1" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.3.1" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha11" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.7.0" }
