name: Build and test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Accept Android SDK licenses
      run: yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.6
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.0
    - name: Build the app
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: :app:assembleDebug
    - name: Run tests
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: |
          :app:phoneDebugAndroidTest
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
