name: PR checks

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3
    - name: Set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        # Avoid downloads by using temurin 17 cached by the runner.
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Accept Android SDK licenses
      run: yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.6
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.5.1
    - name: Build the app
      uses: gradle/gradle-build-action@v2.5.1
      with:
        arguments: :app:assembleDebug
    - name: Run tests
      uses: gradle/gradle-build-action@v2.5.1
      with:
        arguments: |
          :app:phoneDebugAndroidTest
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect

  build-health:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          # Avoid downloads by using temurin 17 cached by the runner.
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.5.1
      - name: Verify build health
        id: build-health
        uses: gradle/gradle-build-action@v2.5.1
        with:
          arguments: :buildHealth
      - name: Build health report
        if: failure() && steps.build-health.outcome == 'failure'
        run: |
          echo "### Build health report" >> $GITHUB_STEP_SUMMARY
          cat "build/reports/dependency-analysis/build-health-report.txt" >> $GITHUB_STEP_SUMMARY
