name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:

    runs-on: macos-12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.159.0
      with:
        bundler-cache: true # Run "bundle install", and cache the result.
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        validate-wrappers: true
    - name: Decrypt secrets
      env:
        GPG_KEY: ${{ secrets.gpg_key }}
      run: ./decrypt.sh
      working-directory: ./secrets
    - name: Build and upload release
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
      run: ci/release-upload.sh
    - name: Archive the release
      uses: actions/upload-artifact@v4.3.3
      with:
        name: apk
        path: secrets/ps42.apk
        if-no-files-found: error
