name: PR checks

on: pull_request

jobs:
  build:

    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Accept Android SDK licenses
      run: yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        validate-wrappers: true
    - name: Build the app
      run: ./gradlew :app:assembleDebug
    - name: Run tests
      run: |
        ./gradlew :app:phoneDebugAndroidTest \
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect \

  build-health:

    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version-file: '.java-version'
          distribution: 'temurin'
          # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
          # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
        with:
          validate-wrappers: true
      - name: Verify build health
        id: build-health
        run: ./gradlew :buildHealth
      - name: Build health report
        if: failure() && steps.build-health.outcome == 'failure'
        run: |
          echo "### Build health report" >> $GITHUB_STEP_SUMMARY
          cat "build/reports/dependency-analysis/build-health-report.txt" | tee -a $GITHUB_STEP_SUMMARY
