name: PR checks

on: pull_request

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.3
    - name: Set up JDK
      uses: actions/setup-java@v4.2.0
      with:
        # Avoid downloads by using temurin 17 cached by the runner.
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Accept Android SDK licenses
      run: yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.1
      with:
        validate-wrappers: true
    - name: Build the app
      run: ./gradlew :app:assembleDebug
    - name: Run tests
      run: |
        ./gradlew :app:phoneDebugAndroidTest \
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect \

  build-health:

    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.3
      - name: Set up JDK
        uses: actions/setup-java@v4.2.0
        with:
          # Avoid downloads by using temurin 17 cached by the runner.
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.1
        with:
          validate-wrappers: true
      - name: Verify build health
        id: build-health
        run: ./gradlew :buildHealth
      - name: Build health report
        if: failure() && steps.build-health.outcome == 'failure'
        run: |
          echo "### Build health report" >> $GITHUB_STEP_SUMMARY
          cat "build/reports/dependency-analysis/build-health-report.txt" | tee -a $GITHUB_STEP_SUMMARY
