name: Release

on:
  push:
    branches: [ "main" ]

# Cancel in-progress/pending daily release workflows if a new one starts.
# When we merge PRs one after another quickly, we only need one release with the latest code.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:

    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Set up Ruby
      uses: ./.github/actions/setup-ruby
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
    - name: Decrypt secrets
      env:
        GPG_KEY: ${{ secrets.gpg_key }}
      run: ./decrypt.sh
      working-directory: ./secrets
    - name: Build and upload release
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
      run: ci/release-upload.sh
    - name: Archive the release
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: apk
        path: secrets/ps42.apk
        if-no-files-found: error
